Repository mozilla/redash-ui-tests, pull requests merged in 2018-10, with the labels that each got.

#80 Fix users API calls
  pages/queries.py
  tests/conftest.py
  tests/test_queries.py
  variables.json
Labels: do not merge

#78 Add run test suite guide.
  docs/tutorials/getting-started.md
Labels: docs

#28 Update Firefox to 61 and geckodriver to 0.22.0
  Dockerfile
Labels: dependencies

#102 added report.html to .dockerignore #100
  .dockerignore
Labels: infra

#103 Adding some additional query tests, as well as some options tests.
  docker-compose.yml
  pages/queries.py
  tests/test_queries.py
  variables.json
Labels: tests
