Repository mozilla/redash-ui-tests, pull requests merged in 2018-06, with the labels that each got.

#29 Add community section to readme
  README.md
Labels: project

#34 Add circle ci config
  .circleci/config.yml
  Makefile
  docker-compose.yml
Labels: infra

#36 Add flake8
  .circleci/config.yml
  Makefile
  Pipfile
  Pipfile.lock
  pages/login.py
  tests/conftest.py
Labels: code quality, infra

#39 Added query search test.
  Makefile
  pages/home.py
  pages/login.py
  pages/queries.py
  tests/conftest.py
  tests/test_login.py
  tests/test_queries.py
  variables.json
Labels: tests

#43 Enable docker uploads.
  .circleci/config.yml
Labels: infra

#44 Start documentation
  docs/index.md
  mkdocs.yml
Labels: docs

#45 Update documentation
  README.md
  docs/about/community.md
  docs/about/project-organization.md
  docs/how-to/select-tests.md
  docs/index.md
  docs/reference/pytest-fixtures.md
  docs/tutorials/developing-tests.md
  docs/tutorials/getting-started.md
  mkdocs.yml
Labels: docs

#52 Run mypy on CI
  .circleci/config.yml
  Makefile
  Pipfile
  Pipfile.lock
  mypy.ini
  tests/conftest.py
Labels: code quality, infra

#51 Add type hints
  models/__init__.py
  models/user.py
  pages/home.py
  pages/login.py
  pages/queries.py
  tests/conftest.py
  tests/test_login.py
  tests/test_queries.py
Labels: code quality
